name: Build Wave Cursor (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    name: Windows
    runs-on: windows-2025-vs2026

    steps:
      - name: Check out source
        uses: actions/checkout@v7

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          cli: latest
          target: Win64
          build-config: Release

      - name: Upload .geode package
        uses: actions/upload-artifact@v7
        with:
          name: WaveCursor-Windows
          path: ${{ steps.build.outputs.build-output }}/*.geode
          if-no-files-found: error
